### PR TITLE
feat: home-manager support

### PR DESCRIPTION
**Pull request by jakehamilton**

### CODE REVIEW

**Comment by khaneliman** [comment]
This seems to work great for setting up darwin and home-manager configurations now, actually. I followed your implementation in your personal config and one thing i'm curious about, though. Is how to reduce redundancy for definitions between darwin, home, and nixos. I assume on the library it is treating each of the modules for darwin, home-manager, and nixos as separate entities but I saw there was a lot of the same syntax and options duplicated between the modules. Is this just a transition thing in your personal config or how it needs to work with the library?

**Comment by Animeshz** [comment]
@khaneliman nixos has `environment.*` and alot of options exclusive to it, whereas home-manager has its own `xdg.*` or `home.*`. How do you plan to use similar modules on both? (I'm not quite too sure about what darwin does)

**Comment by khaneliman** [comment]
@Animeshz I only started working with Nix a few months ago so still learning the basics of everything. That explanation makes sense. The usage i've seen/used is nix-darwin and nixos function similarly using this library. https://github.com/jakehamilton/config/blob/feat/home-manager/modules/darwin/cli-apps/neovim/default.nix vs https://github.com/jakehamilton/config/blob/feat/home-manager/modules/nixos/cli-apps/neovim/default.nix

**Comment by khaneliman** [comment]
@jakehamilton  Is there anything you're waiting for before merging this new configuration into your develop branch?

**Comment by Animeshz** [comment]
I see, nixos and darwin modules do show some similarity, as they both work at system level files.

**Comment by jakehamilton** [comment]
Hey @khaneliman 👋

For the question about module duplication:

I'd originally wanted to provide a way to share a module between systems (NixOS, Darwin, Home-Manager), but there were too many differences to make it practical for more than the most basic module. So I decided to leave that feature on the table. If you really do have a module that shares all of its implementation, you can add a stub for each system that uses `import` to pull in the shared implementation. This is tedious, but better than accidentally publishing broken modules.

For the question about merging this in to develop:

It's close! I'm testing this version on my machines right now to see if there are any bugs. I and @arichtman already found a few and got those worked out. While `dev` is a development branch, I know there are a lot of features there that others are now relying on (like SnowflakeOS). So I don't want to push buggy code there if I can help it.

In addition, I want to make another pass on documentation. I think there is a big gap right now and it could be made a lot easier to understand and get started. Since this branch contains everything that will be in the new Snowfall Lib version, I want to try and polish it up.

**Comment by Animeshz** [comment]
Just for confirmation, I'm also using this branch on my flake: <https://github.com/Animeshz/linux-desktop> no issues so far, except the former review about cfg.name at [modules/home/user/default.nix#L10](https://github.com/snowfallorg/lib/pull/10/files/165d8bb203a6a00670659f03c021e9c580f3f575#diff-6f1455d26683a4b50a4c7faa149972652124276fb3165d4641ef82e95425aaf6) isn't taken into account.

**Comment by khaneliman** [comment]
> > For the question about merging this in to develop:
> > It's close! I'm testing this version on my machines right now to see if there are any bugs. I and @arichtman already found a few and got those worked out. While dev is a development branch, I know there are a lot of features there that others are now relying on (like SnowflakeOS). So I don't want to push buggy code there if I can help it.
> 
> Just for confirmation, I'm also using this branch on my flake: https://github.com/Animeshz/linux-desktop no issues so far, except the former review about cfg.name at [modules/home/user/default.nix#L10](https://github.com/snowfallorg/lib/pull/10/files/165d8bb203a6a00670659f03c021e9c580f3f575#diff-6f1455d26683a4b50a4c7faa149972652124276fb3165d4641ef82e95425aaf6) isn't taken into account.
> 
> And I would like to thank for the tremendous hard-work on making this seamless integration feasible :)

Ditto those sentiments. I finally decided to try out this branch because i had really been wanting to utilize darwin configuration and home-manager specific tasks easier. Was quick and painless transition that seems to work fine using my same flake between my nixos desktop and my macbook. Excited to be able to transition my macbook away from my old dotfiles to my new nix configuration repo.

**Comment by khaneliman** [comment]
@jakehamilton Did you have any issues with your home-manager config on darwin? I realized my home-manager config wasn't applying to my mac and i changed my hostname to be simpler and realized it started triggering the home module evaluation now but fails with a weird error like it's mixing up the system state version and the home module stateversion. 

```
error: A definition for option `home-manager.users.khaneliman.home.stateVersion' is not of type `one of "18.09", "19.03", "19.09", "20.03", "20.09", "21.03", "21.05", "21.11", "22.05", "22.11", "23.05", "23.11"'. Definition values:
       - In `virtual:snowfallorg/home/user/khaneliman@khanelimac': 4
```

**Comment by Animeshz** [comment]
For me as well, something's changed after a recent `nix flake update`, namely

```
$ nix build '.#homeConfigurations.animesh@framework.activation-script'
warning: Git tree '/home/animesh/linux-desktop' is dirty
error: The option `home.username' is used but not defined.
(use '--show-trace' to show detailed location information)
error: Recipe `build` failed on line 5 with exit code 1
```

**Comment by Animeshz** [comment]
@khaneliman Seems like its due to https://github.com/snowfallorg/lib/pull/10/commits/880d907905481fd5360534ba8b2fa11e90cb078c and easist answer is to add

```
  snowfallorg.user.enable = true;
```

to the config, as its now by default false.

**Comment by jakehamilton** [comment]
Ah, thanks for calling this out. This seems like a bug when using home-manager standalone. I'll take a look and see if I can fix it 👍

**Comment by khaneliman** [comment]
Another issue I ran into... i was able to mess up my macbook because i created a config for x86_64-darwin with the same hostname as my aarch64-darwin. A rebuild on my aarch64-darwin  computer apparently used the x86_64 config and now my system is struggling with all kinds of errors because my computer is reporting as x86_64 all of a sudden.. lol

**Comment by jakehamilton** [comment]
@khaneliman that's a good catch. Unfortunately the outputs schema for NixOS and Nix Darwin don't allow for hosts with the same name. I think we could add a check in Snowfall Lib to throw if there is a name collision. That would be better than the user not realizing it.

**Comment by khaneliman** [comment]
> @jakehamilton Did you have any issues with your home-manager config on darwin? I realized my home-manager config wasn't applying to my mac and i changed my hostname to be simpler and realized it started triggering the home module evaluation now but fails with a weird error like it's mixing up the system state version and the home module stateversion.
> 
> ```
> error: A definition for option `home-manager.users.khaneliman.home.stateVersion' is not of type `one of "18.09", "19.03", "19.09", "20.03", "20.09", "21.03", "21.05", "21.11", "22.05", "22.11", "23.05", "23.11"'. Definition values:
>        - In `virtual:snowfallorg/home/user/khaneliman@khanelimac': 4
> ```

Sorry, @jakehamilton I was an idiot.. Finally took a look at this again.... in my config: 
```
khanelinix.home.extraOptions = {
      # home.stateVersion = config.system.stateVersion;
      home.file = mkAliasDefinitions options.khanelinix.home.file;
      xdg.enable = true;
      xdg.configFile = mkAliasDefinitions options.khanelinix.home.configFile;
    };
```
I had at some point uncommented this line out which kept all the home-manager stuff from evaluating in my darwin module because of the system.stateversion being 4 and home-manager state being 2X.XX.

**Pull request merged**
